# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import anycast.anycast_pb2 as anycast__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in anycast_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnycastServiceStub(object):
    """TODO gRPC only supports int32, but the session_id and sequence numbers should both be uint16

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlStream = channel.stream_stream(
                '/AnycastService/ControlStream',
                request_serializer=anycast__pb2.Message.SerializeToString,
                response_deserializer=anycast__pb2.Message.FromString,
                _registered_method=True)
        self.UserRequest = channel.unary_unary(
                '/AnycastService/UserRequest',
                request_serializer=anycast__pb2.Request.SerializeToString,
                response_deserializer=anycast__pb2.Response.FromString,
                _registered_method=True)


class AnycastServiceServicer(object):
    """TODO gRPC only supports int32, but the session_id and sequence numbers should both be uint16

    """

    def ControlStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnycastServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ControlStream,
                    request_deserializer=anycast__pb2.Message.FromString,
                    response_serializer=anycast__pb2.Message.SerializeToString,
            ),
            'UserRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.UserRequest,
                    request_deserializer=anycast__pb2.Request.FromString,
                    response_serializer=anycast__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AnycastService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AnycastService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnycastService(object):
    """TODO gRPC only supports int32, but the session_id and sequence numbers should both be uint16

    """

    @staticmethod
    def ControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/AnycastService/ControlStream',
            anycast__pb2.Message.SerializeToString,
            anycast__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AnycastService/UserRequest',
            anycast__pb2.Request.SerializeToString,
            anycast__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
