# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anycast.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'anycast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranycast.proto\x1a\x19google/protobuf/any.proto\">\n\x07Message\x12\x0c\n\x04type\x18\x01 \x01(\t\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"#\n\x0fRegisterPayload\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"-\n\x0c\x45rrorPayload\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rCancelPayload\"g\n\nJobPayload\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x64st_ip\x18\x02 \x01(\t\x12\x0f\n\x07max_ttl\x18\x03 \x01(\x05\x12\x11\n\tprobe_num\x18\x04 \x01(\x05\x12\x11\n\tbase_port\x18\x05 \x01(\x05\"(\n\x06UdpAck\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\x11\n\tsent_time\x18\x02 \x01(\t\" \n\nAckPayload\x12\x12\n\nsession_id\x18\x01 \x01(\x05\"<\n\x0b\x44onePayload\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x19\n\x08udp_acks\x18\x02 \x03(\x0b\x32\x07.UdpAck\"0\n\x0cReplyPayload\x12\x12\n\nraw_packet\x18\x01 \x01(\x0c\x12\x0c\n\x04time\x18\x02 \x01(\t\",\n\x07Request\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08settings\x18\x02 \x01(\t\"(\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06output\x18\x02 \x01(\t2]\n\x0e\x41nycastService\x12\'\n\rControlStream\x12\x08.Message\x1a\x08.Message(\x01\x30\x01\x12\"\n\x0bUserRequest\x12\x08.Request\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anycast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=44
  _globals['_MESSAGE']._serialized_end=106
  _globals['_REGISTERPAYLOAD']._serialized_start=108
  _globals['_REGISTERPAYLOAD']._serialized_end=143
  _globals['_ERRORPAYLOAD']._serialized_start=145
  _globals['_ERRORPAYLOAD']._serialized_end=190
  _globals['_CANCELPAYLOAD']._serialized_start=192
  _globals['_CANCELPAYLOAD']._serialized_end=207
  _globals['_JOBPAYLOAD']._serialized_start=209
  _globals['_JOBPAYLOAD']._serialized_end=312
  _globals['_UDPACK']._serialized_start=314
  _globals['_UDPACK']._serialized_end=354
  _globals['_ACKPAYLOAD']._serialized_start=356
  _globals['_ACKPAYLOAD']._serialized_end=388
  _globals['_DONEPAYLOAD']._serialized_start=390
  _globals['_DONEPAYLOAD']._serialized_end=450
  _globals['_REPLYPAYLOAD']._serialized_start=452
  _globals['_REPLYPAYLOAD']._serialized_end=500
  _globals['_REQUEST']._serialized_start=502
  _globals['_REQUEST']._serialized_end=546
  _globals['_RESPONSE']._serialized_start=548
  _globals['_RESPONSE']._serialized_end=588
  _globals['_ANYCASTSERVICE']._serialized_start=590
  _globals['_ANYCASTSERVICE']._serialized_end=683
# @@protoc_insertion_point(module_scope)
