// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: anycast.proto

package anycast

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnycastService_ControlStream_FullMethodName = "/AnycastService/ControlStream"
	AnycastService_UserRequest_FullMethodName   = "/AnycastService/UserRequest"
)

// AnycastServiceClient is the client API for AnycastService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnycastServiceClient interface {
	ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
	UserRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type anycastServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnycastServiceClient(cc grpc.ClientConnInterface) AnycastServiceClient {
	return &anycastServiceClient{cc}
}

func (c *anycastServiceClient) ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnycastService_ServiceDesc.Streams[0], AnycastService_ControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnycastService_ControlStreamClient = grpc.BidiStreamingClient[Message, Message]

func (c *anycastServiceClient) UserRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, AnycastService_UserRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnycastServiceServer is the server API for AnycastService service.
// All implementations must embed UnimplementedAnycastServiceServer
// for forward compatibility.
type AnycastServiceServer interface {
	ControlStream(grpc.BidiStreamingServer[Message, Message]) error
	UserRequest(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAnycastServiceServer()
}

// UnimplementedAnycastServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnycastServiceServer struct{}

func (UnimplementedAnycastServiceServer) ControlStream(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Errorf(codes.Unimplemented, "method ControlStream not implemented")
}
func (UnimplementedAnycastServiceServer) UserRequest(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRequest not implemented")
}
func (UnimplementedAnycastServiceServer) mustEmbedUnimplementedAnycastServiceServer() {}
func (UnimplementedAnycastServiceServer) testEmbeddedByValue()                        {}

// UnsafeAnycastServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnycastServiceServer will
// result in compilation errors.
type UnsafeAnycastServiceServer interface {
	mustEmbedUnimplementedAnycastServiceServer()
}

func RegisterAnycastServiceServer(s grpc.ServiceRegistrar, srv AnycastServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnycastServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnycastService_ServiceDesc, srv)
}

func _AnycastService_ControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnycastServiceServer).ControlStream(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnycastService_ControlStreamServer = grpc.BidiStreamingServer[Message, Message]

func _AnycastService_UserRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnycastServiceServer).UserRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnycastService_UserRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnycastServiceServer).UserRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AnycastService_ServiceDesc is the grpc.ServiceDesc for AnycastService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnycastService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AnycastService",
	HandlerType: (*AnycastServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserRequest",
			Handler:    _AnycastService_UserRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlStream",
			Handler:       _AnycastService_ControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "anycast.proto",
}
