// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: anycast.proto

package anycast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *anypb.Any             `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_anycast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_anycast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_anycast_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_anycast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_anycast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_anycast_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_anycast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_anycast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_anycast_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_anycast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_anycast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_anycast_proto_rawDescGZIP(), []int{3}
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int32                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DstIp         string                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	MaxTtl        int32                  `protobuf:"varint,3,opt,name=max_ttl,json=maxTtl,proto3" json:"max_ttl,omitempty"`
	ProbeNum      int32                  `protobuf:"varint,4,opt,name=probe_num,json=probeNum,proto3" json:"probe_num,omitempty"`
	BasePort      int32                  `protobuf:"varint,5,opt,name=base_port,json=basePort,proto3" json:"base_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_anycast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_anycast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_anycast_proto_rawDescGZIP(), []int{4}
}

func (x *Job) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Job) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *Job) GetMaxTtl() int32 {
	if x != nil {
		return x.MaxTtl
	}
	return 0
}

func (x *Job) GetProbeNum() int32 {
	if x != nil {
		return x.ProbeNum
	}
	return 0
}

func (x *Job) GetBasePort() int32 {
	if x != nil {
		return x.BasePort
	}
	return 0
}

type UdpAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	SentTime      string                 `protobuf:"bytes,2,opt,name=sent_time,json=sentTime,proto3" json:"sent_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpAck) Reset() {
	*x = UdpAck{}
	mi := &file_anycast_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpAck) ProtoMessage() {}

func (x *UdpAck) ProtoReflect() protoreflect.Message {
	mi := &file_anycast_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpAck.ProtoReflect.Descriptor instead.
func (*UdpAck) Descriptor() ([]byte, []int) {
	return file_anycast_proto_rawDescGZIP(), []int{5}
}

func (x *UdpAck) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *UdpAck) GetSentTime() string {
	if x != nil {
		return x.SentTime
	}
	return ""
}

type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int32                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UdpAcks       []*UdpAck              `protobuf:"bytes,2,rep,name=udp_acks,json=udpAcks,proto3" json:"udp_acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_anycast_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_anycast_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_anycast_proto_rawDescGZIP(), []int{6}
}

func (x *Done) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Done) GetUdpAcks() []*UdpAck {
	if x != nil {
		return x.UdpAcks
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawPacket     []byte                 `protobuf:"bytes,1,opt,name=raw_packet,json=rawPacket,proto3" json:"raw_packet,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_anycast_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_anycast_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_anycast_proto_rawDescGZIP(), []int{7}
}

func (x *Reply) GetRawPacket() []byte {
	if x != nil {
		return x.RawPacket
	}
	return nil
}

func (x *Reply) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_anycast_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_anycast_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_anycast_proto_rawDescGZIP(), []int{8}
}

func (x *Request) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_anycast_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_anycast_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_anycast_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_anycast_proto protoreflect.FileDescriptor

const file_anycast_proto_rawDesc = "" +
	"\n" +
	"\ranycast.proto\x1a\x19google/protobuf/any.proto\"9\n" +
	"\aMessage\x12.\n" +
	"\apayload\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\"%\n" +
	"\bRegister\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\b\n" +
	"\x06Cancel\"\x8e\x01\n" +
	"\x03Job\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x05R\tsessionId\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\tR\x05dstIp\x12\x17\n" +
	"\amax_ttl\x18\x03 \x01(\x05R\x06maxTtl\x12\x1b\n" +
	"\tprobe_num\x18\x04 \x01(\x05R\bprobeNum\x12\x1b\n" +
	"\tbase_port\x18\x05 \x01(\x05R\bbasePort\"7\n" +
	"\x06UdpAck\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\x12\x1b\n" +
	"\tsent_time\x18\x02 \x01(\tR\bsentTime\"I\n" +
	"\x04Done\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x05R\tsessionId\x12\"\n" +
	"\budp_acks\x18\x02 \x03(\v2\a.UdpAckR\audpAcks\":\n" +
	"\x05Reply\x12\x1d\n" +
	"\n" +
	"raw_packet\x18\x01 \x01(\fR\trawPacket\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\"#\n" +
	"\aRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"6\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output2]\n" +
	"\x0eAnycastService\x12'\n" +
	"\rControlStream\x12\b.Message\x1a\b.Message(\x010\x01\x12\"\n" +
	"\vUserRequest\x12\b.Request\x1a\t.ResponseB.Z,github.com/randofan/voltadomar/proto/anycastb\x06proto3"

var (
	file_anycast_proto_rawDescOnce sync.Once
	file_anycast_proto_rawDescData []byte
)

func file_anycast_proto_rawDescGZIP() []byte {
	file_anycast_proto_rawDescOnce.Do(func() {
		file_anycast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anycast_proto_rawDesc), len(file_anycast_proto_rawDesc)))
	})
	return file_anycast_proto_rawDescData
}

var file_anycast_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_anycast_proto_goTypes = []any{
	(*Message)(nil),   // 0: Message
	(*Register)(nil),  // 1: Register
	(*Error)(nil),     // 2: Error
	(*Cancel)(nil),    // 3: Cancel
	(*Job)(nil),       // 4: Job
	(*UdpAck)(nil),    // 5: UdpAck
	(*Done)(nil),      // 6: Done
	(*Reply)(nil),     // 7: Reply
	(*Request)(nil),   // 8: Request
	(*Response)(nil),  // 9: Response
	(*anypb.Any)(nil), // 10: google.protobuf.Any
}
var file_anycast_proto_depIdxs = []int32{
	10, // 0: Message.payload:type_name -> google.protobuf.Any
	5,  // 1: Done.udp_acks:type_name -> UdpAck
	0,  // 2: AnycastService.ControlStream:input_type -> Message
	8,  // 3: AnycastService.UserRequest:input_type -> Request
	0,  // 4: AnycastService.ControlStream:output_type -> Message
	9,  // 5: AnycastService.UserRequest:output_type -> Response
	4,  // [4:6] is the sub-list for method output_type
	2,  // [2:4] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_anycast_proto_init() }
func file_anycast_proto_init() {
	if File_anycast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anycast_proto_rawDesc), len(file_anycast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anycast_proto_goTypes,
		DependencyIndexes: file_anycast_proto_depIdxs,
		MessageInfos:      file_anycast_proto_msgTypes,
	}.Build()
	File_anycast_proto = out.File
	file_anycast_proto_goTypes = nil
	file_anycast_proto_depIdxs = nil
}
