# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anycast.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'anycast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranycast.proto\x12\x07\x61nycast\"9\n\x0bInitRequest\x12\x0c\n\x04hmac\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ilter\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\"\"\n\x0bSendRequest\x12\x13\n\x0braw_request\x18\x01 \x01(\x0c\"F\n\rForwardPacket\x12\x11\n\traw_reply\x18\x01 \x01(\x0c\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x14\n\x0creceive_time\x18\x03 \x01(\t\"2\n\x0f\x43ommandResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x11\n\tsent_time\x18\x02 \x01(\t2\x93\x01\n\x0e\x41nycastService\x12\x41\n\rReceiverAgent\x12\x14.anycast.InitRequest\x1a\x16.anycast.ForwardPacket\"\x00\x30\x01\x12>\n\nSendPacket\x12\x14.anycast.SendRequest\x1a\x18.anycast.CommandResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anycast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITREQUEST']._serialized_start=26
  _globals['_INITREQUEST']._serialized_end=83
  _globals['_SENDREQUEST']._serialized_start=85
  _globals['_SENDREQUEST']._serialized_end=119
  _globals['_FORWARDPACKET']._serialized_start=121
  _globals['_FORWARDPACKET']._serialized_end=191
  _globals['_COMMANDRESPONSE']._serialized_start=193
  _globals['_COMMANDRESPONSE']._serialized_end=243
  _globals['_ANYCASTSERVICE']._serialized_start=246
  _globals['_ANYCASTSERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
