# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import anycast_pb2 as anycast__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in anycast_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnycastServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiverAgent = channel.unary_stream(
                '/anycast.AnycastService/ReceiverAgent',
                request_serializer=anycast__pb2.InitRequest.SerializeToString,
                response_deserializer=anycast__pb2.ForwardPacket.FromString,
                _registered_method=True)
        self.SendPacket = channel.unary_unary(
                '/anycast.AnycastService/SendPacket',
                request_serializer=anycast__pb2.SendRequest.SerializeToString,
                response_deserializer=anycast__pb2.CommandResponse.FromString,
                _registered_method=True)


class AnycastServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiverAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPacket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnycastServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiverAgent': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiverAgent,
                    request_deserializer=anycast__pb2.InitRequest.FromString,
                    response_serializer=anycast__pb2.ForwardPacket.SerializeToString,
            ),
            'SendPacket': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPacket,
                    request_deserializer=anycast__pb2.SendRequest.FromString,
                    response_serializer=anycast__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'anycast.AnycastService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('anycast.AnycastService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnycastService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiverAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/anycast.AnycastService/ReceiverAgent',
            anycast__pb2.InitRequest.SerializeToString,
            anycast__pb2.ForwardPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPacket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/anycast.AnycastService/SendPacket',
            anycast__pb2.SendRequest.SerializeToString,
            anycast__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
